name: Build Kivy APK

on:
  push:
    branches:
      - main # Adjust to your target branch

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      # Install dependencies
      - name: Install Buildozer and dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-pip python3-venv git zip unzip openjdk-11-jdk cython3
          pip install --upgrade buildozer

      # Install Android SDK
      - name: Setup Android SDK
        uses: android-actions/sdk-setup@v2
        with:
          android-version: "33" # Adjust according to your app's requirements
          build-tools-version: "33.0.0" # Specify the required build-tools version

      # Initialize Buildozer
      - name: Initialize Buildozer
        run: |
          buildozer init
          sed -i 's/^source.include_exts/# source.include_exts/' buildozer.spec
          sed -i 's/^source.exclude_exts/# source.exclude_exts/' buildozer.spec
          echo "source.include_exts = py, kv" >> buildozer.spec
          echo "title = My Kivy App" >> buildozer.spec

      # Build the APK
      - name: Build APK
        run: |
          export ANDROID_HOME=$ANDROID_SDK_ROOT
          export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$PATH
          buildozer android debug

      # Upload the APK as an artifact
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: Kivy-App-APK
          path: bin/*.apk
