name: Build Kivy APK

on:
  push:
    branches:
      - main # Adjust this to your target branch

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9" # Specify the Python version

      # Install dependencies
      - name: Install Buildozer and dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-pip python3-venv git zip unzip openjdk-11-jdk
          pip install --upgrade buildozer

      # Initialize Buildozer
      - name: Initialize Buildozer
        run: |
          buildozer init
          sed -i 's/^source.include_exts/# source.include_exts/' buildozer.spec  # Disable source.include_exts
          sed -i 's/^source.exclude_exts/# source.exclude_exts/' buildozer.spec  # Disable source.exclude_exts
          echo "source.include_exts = py, kv" >> buildozer.spec                  # Include app.py and KV files
          echo "title = My Kivy App" >> buildozer.spec                          # Set app title

      # Build the APK
      - name: Build APK
        run: buildozer android debug

      # Upload the APK as an artifact
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: Kivy-App-APK
          path: bin/*.apk # Adjust path if necessary
