name: Build APK
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip build-essential git python3 python3-dev ffmpeg libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev libportmidi-dev libswscale-dev libavformat-dev libavcodec-dev zlib1g-dev
          sudo apt-get install -y libgstreamer1.0-dev gstreamer1.0-plugins-{bad,base,good,ugly} gstreamer1.0-{tools,x} libzbar-dev

      - name: Install Buildozer
        run: |
          python -m pip install --upgrade pip
          pip install buildozer
          pip install cython

      - name: Install Android SDK
        run: |
          sudo apt-get install -y openjdk-8-jdk
          wget https://dl.google.com/android/repository/commandlinetools-linux-6609375_latest.zip
          mkdir -p $HOME/android-sdk/cmdline-tools
          unzip commandlinetools-linux-6609375_latest.zip -d $HOME/android-sdk/cmdline-tools
          mkdir -p $HOME/android-sdk/cmdline-tools/latest
          mv $HOME/android-sdk/cmdline-tools/tools/* $HOME/android-sdk/cmdline-tools/latest/
          yes | $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager --licenses
          $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager "platform-tools" "platforms;android-29" "build-tools;29.0.3"
        env:
          ANDROID_HOME: $HOME/android-sdk

      - name: Create buildozer.spec if not exists
        run: |
          if [ ! -f buildozer.spec ]; then
            buildozer init
            sed -i 's/^title =.*/title = MyKivyApp/' buildozer.spec
            sed -i 's/^package.name =.*/package.name = mykivyapp/' buildozer.spec
            sed -i 's/^source.include_exts =.*/source.include_exts = py,png,jpg,kv,atlas,json/' buildozer.spec
            sed -i 's/^requirements =.*/requirements = python3,kivy/' buildozer.spec
          fi

      - name: Build APK
        run: buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: app-debug
          path: bin/*.apk
