name: Build BeeWare App to APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install briefcase

      - name: Build APK
        run: |
          briefcase create android
          briefcase build android

      - name: Upload APK as artifact
        uses: actions/upload-artifact@v2
        with:
          name: app.apk
          path: build/*/android/gradle/app/build/outputs/apk/debug/app-debug.apk
